[build.environment]
	NPM_FLAGS = "--version" # prevent Netlify npm install

[build]
	command = "npx pnpm i --store=node_modules/.pnpm-store && npm run client:build"
	publish = "dist"

[[redirects]]
	from = "/*"
	to = "/index.html"
	status = 200
